package ipu.example.demo.mapper;

import ipu.example.demo.dto.TutorialDto;
import ipu.example.demo.model.Tutorial;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import org.mapstruct.Mapper;

/**
 * MapStruct mapper interface for converting between {@link Tutorial} entities and {@link TutorialDto} DTOs.
 * <p>
 * This mapper helps to isolate domain models from transport-layer objects.
 * Implementations are automatically generated by MapStruct at build time.
 */
@Mapper
public interface TutorialMapper {

 /**
  * Maps a {@link Tutorial} entity to a {@link TutorialDto}.
  *
  * @param tutorial the entity to convert
  * @return the mapped DTO
  */
 TutorialDto tutorialToDto(Tutorial tutorial);

 /**
  * Maps a list of {@link Tutorial} entities to a list of {@link TutorialDto}.
  *
  * @param tutorials the list of entities to convert
  * @return the list of mapped DTOs
  */
 List<TutorialDto> tutorialsToDtos(@NotNull List<Tutorial> tutorials);

 /**
  * Maps a {@link TutorialDto} to a {@link Tutorial} entity.
  *
  * @param dto the DTO to convert
  * @return the mapped entity
  */
 Tutorial dtoToTutorial(@NotNull TutorialDto dto);
}
